// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://otjtbhrwoxhdsxfvoigr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im90anRiaHJ3b3hoZHN4ZnZvaWdyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0NDEyNDEsImV4cCI6MjA3MzAxNzI0MX0.LvqpJAi1P_lIgiElFCQa7bcmpatBcYMjXGCOskPReRI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});